version: 2.1

jobs:
  install-and-build:
    docker:
      - image: cimg/node:18.0.0
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-9 --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install Dependencies
          command: pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store
      - run:
          name: Build user app
          command: pnpm --filter user build
      - run:
          name: Build Storybook
          command: pnpm --filter @packages/components build-storybook
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint user app
          command: pnpm --filter user lint
      - run:
          name: Lint components package
          command: pnpm --filter @packages/components lint

  deploy-chromatic:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Chromatic
          command: pnpm --filter @packages/components chromatic

  preview-user-app:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Preview user app
          command: pnpm --filter user preview
          background: true
      - run:
          name: Wait for preview server
          command: |
            timeout 60s bash -c '
            until curl -s --head --request GET localhost:4173 | grep "200 OK"; do
              echo "Waiting for preview server..."
              sleep 5
            done
            '

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - install-and-build
      - lint:
          requires:
            - install-and-build
      - deploy-chromatic:
          requires:
            - lint
          filters:
            branches:
              only: main
      - preview-user-app:
          requires:
            - lint