name: 빌드

on:
  push:
    branches:
      - main
      - develop
  pull_request_target:
    branches:
      - main
      - develop
      
permissions:
      id-token: write
      contents: read
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pnpm 설치
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          
      - name: Node.js 설치
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: 종속 패키지 설치
        run: pnpm install

  build:
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pnpm 설치
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          
      - name: Node.js 설치
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: 환경 변수 파일 생성
        run: |
          cd ./apps/user/
          touch .env
          echo VITE_BASE_URL=${{ secrets.VITE_BASE_URL }} >> .env
          echo VITE_OAUTH_CLIENT_ID=${{ secrets.VITE_OAUTH_CLIENT_ID }} >> .env
          echo VITE_OAUTH_CLIENT_SECRET=${{ secrets.VITE_OAUTH_CLIENT_SECRET }} >> .env
          cat .env
          
      - name: 종속 패키지 설치
        run: pnpm install

      - name: 빌드 시작
        run: pnpm build
        
      - name: AWS Credential 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          
      - name: S3 배포
        run: |
          aws s3 sync ./apps/user/dist s3://${{ secrets.AWS_STAGING_BUCKET_NAME }} --delete --acl public-read

