name: 콘솔 로그 확인

on: [pull_request]

jobs:
  inspect:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 메인 브랜치 최신 코드를 가져옵니다.
        run: git fetch origin main

      - name: Check console.log
        run: |
          if bash .scripts/is_contain.sh "^\+.*(console\.log)"; then
            echo "console.log is used, please remove it before merging";
            gh pr comment $PR_URL --body "There is console.log on your commit. Please remove it before merge."
            exit 1;
          fi
