name: CI

on:
  push:
    branches:
      - main
      - develop
      - feat-*

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: pnpm을 설치합니다.
        with:
          run_install: false

      - name: Node.js를 설치합니다.
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 의존 패키지를 설치합니다
        run: pnpm install

  lint:
    runs-on: ubuntu-latest
    needs: cache-and-install

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: pnpm을 설치합니다. 
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Node.js를 설치합니다.
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: 의존 패키지를 설치합니다
        run: pnpm install

      - name: ESLINT를 실행합니다.
        run: pnpm run lint